import type { Metadata } from "next";
import "./globals.css";

import { Inter as FontSans } from "next/font/google"

import { cn } from "@/lib/utils"
import { ThemeProvider } from "@/components/themeProvider";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "NextJS shadcn/ui",
  description: "Generated by create next app+shadcn/ui",
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          "min-h-screen dark:bg-zinc-700 dark:text-zinc-400 font-sans antialiased bg-zinc-300 text-zinc-700",
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
        >
          {children}

        </ThemeProvider>
      </body>


    </html>
  )
}

